name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Remove default Nginx welcome page
      run: ssh ${{ secrets.USER }}@${{ secrets.INSTANCE_HOST }} "sudo rm /var/www/html/index.nginx-debian.html"

    - name: Copy HTML file to EC2
      run: scp -r ./index.html ${{ secrets.USER }}@${{ secrets.INSTANCE_HOST }}:/var/www/html

    - name: Restart Nginx
      run: ssh ${{ secrets.USER }}@${{ secrets.INSTANCE_HOST }} "sudo systemctl restart nginx"
