name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove existing code
        run: |
            if [ "ls | grep ga-demo-html" ]
            then 
              rm -rf ga-demo-html
            fi

      - name: Cloning the code
        run: git clone https://github.com/IshThumber/ga-demo-html.git

      - name: Check if www/html contains HTML file or not
        run: sudo rm /var/www/html/*.html

      - name: Change the location of HTML
        run: sudo mv ga-demo-html/index.html /var/www/html/
      
      - name: Restart Nginx
        run: sudo systemctl restart nginx
