name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_PRIVATE_KEY: ${{secrets.INSTANCE_HOST}}
            USER: ${{secrets.USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${INSTANCE_HOST} '


      - name : Hostname
        run  : echo "$(hostname -f)"
      
      - name: Crete
        run : sudo mkdir folder
        
      # - name: Remove existing github code
      #   run: |
      #       if [ "ls | grep ga-demo-html" ]
      #       then 
      #         sudo rm -rf ga-demo-html
      #       fi

      # - name: Cloning the repo
      #   run: sudo git clone https://github.com/IshThumber/ga-demo-html.git

      # - name: Remove html file if present in /var/www/html
      #   run: sudo rm /var/www/html/*.html

      # - name: Change the location of HTML
      #   run: sudo mv ga-demo-html/index.html /var/www/html/

      # - name: Restart Apache2
      #   run: sudo systemctl restart apache2
